name: Github Pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - beta

jobs:
  pages:
    name: Github Pages
    runs-on: ubuntu-latest
    concurrency: ci-pages-${{ github.ref }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository - Main
        uses: actions/checkout@v6
        with:
          ref: main
          path: main
      
      - name: Checkout Repository - Beta
        uses: actions/checkout@v6
        with:
          ref: beta
          path: beta

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        working-directory: ./main
        run: pnpm install --filter client --filter shared --filter server

      - name: Restore Atlas Cache
        id: cache-atlases-restore
        uses: actions/cache@v4
        if: always()
        with:
          path: ./main/client/node_modules/.atlas-cache/
          key: atlas-cache-main-${{ github.run_id }}
          restore-keys: |
            atlas-cache-main

      - name: Build Client
        run: pnpm run build
        working-directory: ./main/client
        if: always()
      - name: Save Atlas Cache
        id: cache-atlases-save
        uses: actions/cache/save@v4
        with:
          path: ./main/client/node_modules/.atlas-cache/
          key: atlas-cache-main-${{ github.run_id }}

      # -------------------------
      # Beta build
      # -------------------------

      - name: Install Beta Packages
        working-directory: ./beta
        run: pnpm install --filter client --filter shared --filter server

      - name: Restore Beta Atlas Cache
        uses: actions/cache@v4
        with:
          path: ./beta/client/node_modules/.atlas-cache/
          key: atlas-cache-beta-${{ github.run_id }}
          restore-keys: |
            atlas-cache-beta-

      - name: Build Beta Client
        working-directory: ./beta/client
        run: pnpm run build

      - name: Save Beta Atlas Cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ./beta/client/node_modules/.atlas-cache/
          key: atlas-cache-beta-${{ github.run_id }}
      
      # -------------------------
      # Combine builds
      #
      # pages/
      #   index.html       <- main
      #   assets/
      #   beta/
      #     index.html     <- beta
      #     assets/
      # -------------------------

      - name: Assemble Pages
        run: |
          mkdir -p ./pages
          cp -r ./main/client/dist/. ./pages/

          mkdir -p ./pages/beta
          cp -r ./beta/client/dist/. ./pages/beta/
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./client/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
